[package]
name = "pact"
version = "1.0.0"
authors = []

[addresses]
pact_addr = "_"

[dev-addresses]
pact_addr = "0xCAFE"

[dependencies.AptosFramework]
git = "https://github.com/movementlabsxyz/aptos-core.git"
rev = "movement"
subdir = "aptos-move/framework/aptos-framework"

[dev-dependencies]
